apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-batch-ita-v2
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/batch/*.log
        Parser            batch_parser
        Tag               batch-ita-v2.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name                cloudwatch_logs
        Match               *
        region              ap-northeast-1
        log_group_name      /aws/eks/dev-bizportal-eks-cluster-01/batch-ita-v2
        log_stream_prefix   ${POD_NAME}-
        auto_create_group   true

  parsers.conf: |
    [PARSER]
        Name        batch_parser
        Format      regex
        Regex       ^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?<level>\w+)\s+\[(?<logger>[^\]]+)\] \((?<thread>[^)]+)\) (?<message>.*)
        Time_Key    timestamp
        Time_Format %Y-%m-%d %H:%M:%S,%L